/*
 * sandlock C API — opaque handle bindings to sandlock-core.
 *
 * GENERATED BY cbindgen. DO NOT EDIT THIS FILE BY HAND.
 * See crates/sandlock-ffi/cbindgen.toml for the regeneration command.
 *
 * All pointer types are opaque handles; free each with its _free().
 * Builder functions consume and return the builder (move semantics).
 */

#ifndef SANDLOCK_H
#define SANDLOCK_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

typedef struct sandlock_builder_t sandlock_builder_t;
typedef struct sandlock_t sandlock_t;
typedef struct sandlock_sandbox_t sandlock_sandbox_t;
typedef struct sandlock_result_t sandlock_result_t;
typedef struct sandlock_handler_t sandlock_handler_t;


/**
 * `flags` bit for [`sandlock_action_set_inject_bytes`]: leave the injected
 * memfd writable (do not seal). Default (bit clear) seals it read-only.
 */
#define SANDLOCK_INJECT_WRITABLE (1 << 0)

/**
 * `flags` bit for [`sandlock_action_set_inject_bytes`]: do not set
 * `O_CLOEXEC` on the child-side fd. Default (bit clear) sets `O_CLOEXEC`.
 */
#define SANDLOCK_INJECT_NO_CLOEXEC (1 << 1)

/**
 * `err` value meaning the transaction handle was null: a bug in the calling
 * binding, not a failed transaction. No message accompanies it.
 *
 * Negative, and so outside `sandlock_txn_err_t`, on purpose: nothing was
 * attempted, so there is no verdict on a workdir to report.
 */
#define SANDLOCK_TXN_NULL_HANDLE -1

/**
 * `err` value meaning this thread's async runtime could not be built, or it
 * panicked while driving the transaction. No message accompanies it; the
 * cause has already been reported on this process's file descriptor 2.
 *
 * Negative for the same reason as `SANDLOCK_TXN_NULL_HANDLE`, though here the
 * transaction may well have run: nothing can be said about the workdir from
 * here, which is precisely why it is not one of the named verdicts.
 */
#define SANDLOCK_TXN_NO_RUNTIME -2

/**
 * Why a sandboxed process terminated. `EXITED` carries an exit code
 * (`sandlock_result_exit_code`); `SIGNALED` carries the signal number
 * (`sandlock_result_signal`). Linux bottoms both a timeout and an OOM kill out
 * in `SIGKILL`, so there is no distinct OOM reason: a timeout sandlock enforced
 * is `TIMEOUT`, any other kill is `KILLED`.
 */
enum sandlock_exit_reason
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * Exited normally with a code (`sandlock_result_exit_code`).
   */
  SANDLOCK_EXIT_REASON_EXITED = 0,
  /**
   * Terminated by a signal (`sandlock_result_signal`).
   */
  SANDLOCK_EXIT_REASON_SIGNALED = 1,
  /**
   * Killed with no recoverable signal number.
   */
  SANDLOCK_EXIT_REASON_KILLED = 2,
  /**
   * Killed by sandlock because it exceeded its timeout.
   */
  SANDLOCK_EXIT_REASON_TIMEOUT = 3,
};
#ifndef __cplusplus
typedef uint32_t sandlock_exit_reason;
#endif // __cplusplus

/**
 * Tag distinguishing payload variants of `sandlock_action_out_t`.
 */
enum sandlock_action
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * No action set yet; the supervisor treats this as "fall through to
   * the handler's on_exception policy" (see `exception_action` in
   * `FfiHandler`).
   */
  SANDLOCK_ACTION_UNSET = 0,
  SANDLOCK_ACTION_CONTINUE = 1,
  SANDLOCK_ACTION_ERRNO = 2,
  SANDLOCK_ACTION_RETURN_VALUE = 3,
  SANDLOCK_ACTION_INJECT_FD_SEND = 4,
  SANDLOCK_ACTION_INJECT_FD_SEND_TRACKED = 5,
  SANDLOCK_ACTION_HOLD = 6,
  SANDLOCK_ACTION_KILL = 7,
};
#ifndef __cplusplus
typedef uint32_t sandlock_action;
#endif // __cplusplus

/**
 * Exception policy applied when the handler callback fails to set a
 * valid action (returns non-zero rc, leaves `kind == Unset`, or panics
 * across the FFI boundary).
 */
enum sandlock_exception
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * Treat the failure as `NotifAction::Kill { sig: SIGKILL, pgid: child_pgid }`.
   * Default; "fail-closed" — the safe option.
   */
  SANDLOCK_EXCEPTION_KILL = 0,
  /**
   * Treat the failure as `NotifAction::Errno(EPERM)`. Useful for
   * audit-style handlers where the syscall is what failed rather than
   * the supervisor.
   */
  SANDLOCK_EXCEPTION_DENY_EPERM = 1,
  /**
   * Treat the failure as `NotifAction::Continue`. Explicit fail-open;
   * only safe when the syscall is *also* allowed by the BPF filter and
   * Landlock layer (e.g. observability handlers).
   */
  SANDLOCK_EXCEPTION_CONTINUE = 2,
  /**
   * Treat the failure as `NotifAction::Errno(EIO)`. Idiomatic for
   * audit-only handlers: EIO propagates to the caller as a plain
   * `OSError` rather than `PermissionError`, which is closer to what
   * callers expect from a failed syscall.
   */
  SANDLOCK_EXCEPTION_DENY_EIO = 3,
};
#ifndef __cplusplus
typedef uint32_t sandlock_exception;
#endif // __cplusplus

/**
 * How a transaction ended, as reported through the `err` out-parameter of
 * [`sandlock_txn_run`] and [`sandlock_txn_dry_run`].
 *
 * The list is append only: a published value never changes meaning, and a
 * caller that meets a value it does not know must treat it as a failure it
 * cannot classify rather than as success.
 *
 * Two of these are easy to mistake for each other and mean opposite things.
 * `SANDLOCK_TXN_CONFLICT` is the retryable one (another commit held the
 * lock); `SANDLOCK_TXN_COMMIT_LOCK` is not (the lock could not be taken at
 * all).
 *
 * The two negative codes that can also appear in `err` are deliberately not
 * members: they are not verdicts on a transaction, so they must not be
 * switched on alongside these. See `SANDLOCK_TXN_NULL_HANDLE` and
 * `SANDLOCK_TXN_NO_RUNTIME`.
 */
enum sandlock_txn
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * The transaction ran. An outcome handle was returned; its disposition
   * says whether it committed.
   */
  SANDLOCK_TXN_OK = 0,
  /**
   * The stage set is not a valid transaction. Checked before anything runs.
   */
  SANDLOCK_TXN_INVALID = 1,
  /**
   * The shared copy-on-write branch could not be created. No stage ran.
   */
  SANDLOCK_TXN_BRANCH = 2,
  /**
   * A stage could not be started or driven to completion. This is not a
   * stage that FAILED: a non-zero exit is an aborted outcome, not an error.
   */
  SANDLOCK_TXN_STAGE = 3,
  /**
   * Contention: another commit held the workdir lock for longer than
   * [`sandlock_txn_commit_lock_wait_ms`]. The workdir is untouched and the
   * whole change set was preserved. Retrying is the expected response.
   */
  SANDLOCK_TXN_CONFLICT = 4,
  /**
   * The workdir commit lock could not be taken for a reason other than
   * contention (the workdir could not be opened, or `flock` failed). As
   * with `SANDLOCK_TXN_CONFLICT` the workdir is untouched and the change
   * set was preserved.
   */
  SANDLOCK_TXN_COMMIT_LOCK = 5,
  /**
   * The commit merge failed. The merge is not rolled back, so the workdir
   * may be partially merged, and what did not land was preserved WHEN a
   * marker could be written for it. Failing to write that marker is itself
   * one of the ways this failure is reached, and in that case the workdir
   * was not touched at all and no sweep will ever find the change set. The
   * message says which of the two happened, so read it before acting.
   */
  SANDLOCK_TXN_MERGE = 6,
  /**
   * The commit phase never ran to completion because the runtime was shut
   * down under it. This is the one failure that cannot say what state the
   * workdir and the change set are in.
   */
  SANDLOCK_TXN_COMMIT_ABANDONED = 7,
  /**
   * A failure this version of the ABI has no name for. The core failure set
   * is open, so a binding built against an older header can meet a newer
   * core; the message still carries the core's own explanation.
   */
  SANDLOCK_TXN_UNKNOWN = 8,
};
#ifndef __cplusplus
typedef uint32_t sandlock_txn;
#endif // __cplusplus

/**
 * Which terminal state a transaction that ran ended in, as reported by
 * [`sandlock_txn_outcome_disposition`].
 *
 * Unlike `sandlock_txn_err_t` this set is not append only, it is TOTAL: a
 * transaction that ran ended in exactly one of these three, so a caller may
 * switch on it exhaustively and need no default arm. The core keeps it that
 * way on purpose, by funnelling future abort causes through the reason an
 * abort carries rather than through a fourth state.
 *
 * `sandlock_txn_outcome_disposition` returns -1 for a null outcome, which is
 * not a member: it says there was no transaction to have a disposition.
 */
enum sandlock_txn_disposition
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * Every stage exited 0 and the shared upper was merged into the workdir.
   */
  SANDLOCK_TXN_DISPOSITION_COMMITTED = 0,
  /**
   * Every stage exited 0 and the upper was discarded on purpose: the run
   * was a dry run, so the workdir was never written to.
   */
  SANDLOCK_TXN_DISPOSITION_DRY_RUN = 1,
  /**
   * A stage exited non-zero, or the stage phase timed out. The upper was
   * discarded and the workdir is untouched. Which of the two happened is
   * not published as a value; see [`sandlock_txn_outcome_disposition`].
   */
  SANDLOCK_TXN_DISPOSITION_ABORTED = 2,
};
#ifndef __cplusplus
typedef uint32_t sandlock_txn_disposition;
#endif // __cplusplus

/**
 * Why a change set was left in branch storage instead of being reclaimed, as
 * reported by [`sandlock_preserved_reason`].
 *
 * This is what says how far the workdir got, so it decides what a recovery
 * may do rather than merely describing history. The list is append only.
 *
 * `sandlock_preserved_reason` returns -1 for a null record, which is not a
 * member: it says the question was not asked of a record at all.
 */
enum sandlock_preserve
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  /**
   * A merge started and did not finish, so the workdir may be partly
   * merged. A merge that is STILL RUNNING is indistinguishable from this:
   * the marker is written before the first destructive step. Check
   * [`sandlock_preserved_pid`] before acting on such a record.
   */
  SANDLOCK_PRESERVE_MERGE_INTERRUPTED = 0,
  /**
   * A commit could not take the workdir lock. The workdir is untouched and
   * the whole change set is here.
   */
  SANDLOCK_PRESERVE_COMMIT_DEFERRED = 1,
  /**
   * The caller asked for the branch to be kept.
   */
  SANDLOCK_PRESERVE_KEPT = 2,
};
#ifndef __cplusplus
typedef uint32_t sandlock_preserve;
#endif // __cplusplus

/**
 * Opaque handle wrapping a [`Checkpoint`].
 */
typedef struct sandlock_checkpoint_t sandlock_checkpoint_t;

/**
 * C-compatible policy context handle.
 */
typedef struct sandlock_ctx_t sandlock_ctx_t;

/**
 * Opaque dry-run result.
 */
typedef struct sandlock_dry_run_result_t sandlock_dry_run_result_t;

/**
 * Opaque handle for fork result (holds clone handles with pipes).
 */
typedef struct sandlock_fork_result_t sandlock_fork_result_t;

typedef struct sandlock_gather_t sandlock_gather_t;

/**
 * Opaque handle for a live sandbox.
 *
 * Owns both the Sandbox and a small Tokio runtime that drives its
 * supervisor. Live handles need a runtime whose spawned tasks keep
 * progressing after `sandlock_start` returns.
 */
typedef struct sandlock_handle_t sandlock_handle_t;

/**
 * Opaque handle wrapping a [`Pipeline`].
 */
typedef struct sandlock_pipeline_t sandlock_pipeline_t;

/**
 * Opaque handle holding one sweep of a storage base.
 *
 * Owns its entries, so every pointer handed out by
 * [`sandlock_preserved_list_at`] dies with it. Release it with
 * [`sandlock_preserved_list_free`].
 */
typedef struct sandlock_preserved_list_t sandlock_preserved_list_t;

/**
 * Opaque handle holding one preserved change set: work that was left in
 * branch storage instead of being reclaimed, because a commit could not take
 * the workdir lock, a merge stopped partway, or the caller asked for it to be
 * kept.
 *
 * There are two producers and they have DIFFERENT release rules.
 * [`sandlock_preserved_read`] returns an OWNED handle that the caller
 * releases with [`sandlock_preserved_free`].
 * [`sandlock_preserved_list_at`] returns a BORROW of an entry inside a list,
 * which must never reach [`sandlock_preserved_free`]: it is released by
 * [`sandlock_preserved_list_free`] together with the rest of the list.
 *
 * Every accessor below works on either kind, and every string it returns is
 * owned by the caller in both cases.
 */
typedef struct sandlock_preserved_t sandlock_preserved_t;

/**
 * Opaque handle holding the outcome of a transaction.
 *
 * Produced by [`sandlock_txn_run`] and [`sandlock_txn_dry_run`], released
 * with [`sandlock_txn_outcome_free`]. It owns the per-stage results and the
 * change list, so every pointer handed out by
 * [`sandlock_txn_outcome_stage_at`] dies with it.
 */
typedef struct sandlock_txn_outcome_t sandlock_txn_outcome_t;

/**
 * Opaque handle wrapping a transaction under construction.
 *
 * Create it with [`sandlock_txn_new`]. It is consumed by a run; a
 * transaction that is built and then abandoned must be released with
 * [`sandlock_txn_free`].
 */
typedef struct sandlock_txn_t sandlock_txn_t;

/**
 * C-compatible syscall event passed to the policy callback.
 *
 * Path strings are intentionally absent (issue #27); use static Landlock
 * rules for path-based access control. argv is exposed for execve only
 * and is TOCTOU-safe via sibling-thread freeze before Continue.
 */
typedef struct {
  const char *syscall;
  /**
   * Category: 0=File, 1=Network, 2=Process, 3=Memory
   */
  uint8_t category;
  uint32_t pid;
  uint32_t parent_pid;
  const char *host;
  uint16_t port;
  bool denied;
  const char *const *argv;
  uint32_t argc;
} sandlock_event_t;

/**
 * C callback type for policy_fn.
 * Return value: 0 = allow, -1 = deny (EPERM), -2 = audit (allow + flag),
 * positive = deny with that errno (e.g. 13 = EACCES). Any other value fails
 * closed (deny); do not return `-errno`, which is reserved and not allowed.
 */
typedef int32_t (*sandlock_policy_fn_t)(const sandlock_event_t *event,
                                        sandlock_ctx_t *ctx,
                                        void *user_data);

/**
 * C callback types for fork init and work functions.
 */
typedef void (*sandlock_init_fn_t)(void);

typedef void (*sandlock_work_fn_t)(uint32_t clone_id);

/**
 * Opaque child-memory accessor handed to a C handler callback.
 *
 * Constructed on the stack inside the Rust adapter just before the
 * callback fires, invalidated when the callback returns. C handlers
 * must not store the pointer beyond the callback's return.
 */
typedef struct {
  int notif_fd;
  uint64_t notif_id;
  uint32_t pid;
} sandlock_mem_handle_t;

typedef struct {
  /**
   * Owned by the C caller; ownership transfers to the supervisor on
   * successful invocation of the corresponding setter.
   */
  int32_t srcfd;
  uint32_t newfd_flags;
} sandlock_action_inject_t;

/**
 * Token reserved for a future tracker-aware inject variant. Currently
 * unimplemented — kept as a type alias so the ABI of the
 * `sandlock_action_inject_tracked_t` payload stays stable across the
 * future release that wires the tracker callback.
 */
typedef uint64_t sandlock_inject_tracker_t;

typedef struct {
  int32_t srcfd;
  uint32_t newfd_flags;
  sandlock_inject_tracker_t tracker;
} sandlock_action_inject_tracked_t;

typedef struct {
  int32_t sig;
  int32_t pgid;
} sandlock_action_kill_t;

typedef union {
  uint64_t none;
  /**
   * `errno_value` rather than `errno` to mirror the C header field
   * (the C side avoids the name `errno` because `<errno.h>` macros
   * it). Keeping both languages in sync removes a documentation
   * hazard for callers that grep across Rust and C sources.
   */
  int32_t errno_value;
  int64_t return_value;
  sandlock_action_inject_t inject_send;
  sandlock_action_inject_tracked_t inject_send_tracked;
  sandlock_action_kill_t kill;
} sandlock_action_payload_t;

typedef struct {
  uint32_t kind;
  sandlock_action_payload_t payload;
} sandlock_action_out_t;

/**
 * Stable wire-layout snapshot of a seccomp notification.
 *
 * Field order, types, and padding must match `sandlock.h` exactly. The
 * size assertion in `tests/handler_smoke.rs` guards against accidental
 * drift; if a new field is added, bump the documented size and update
 * the C header in the same commit.
 */
typedef struct {
  uint64_t id;
  uint32_t pid;
  uint32_t flags;
  int32_t syscall_nr;
  uint32_t arch;
  uint64_t instruction_pointer;
  uint64_t args[6];
} sandlock_notif_data_t;

/**
 * C-side pair of `(syscall_nr, handler*)` consumed by
 * `sandlock_run_with_handlers`. Ownership of `handler` transfers into
 * the run on success; the supervisor frees the container.
 */
typedef struct {
  int64_t syscall_nr;
  sandlock_handler_t *handler;
} sandlock_handler_registration_t;

/**
 * C destructor type for policy_fn user data.
 *
 * Called when the native policy callback is dropped. This may be later than a
 * single run when the policy has been cloned; it fires once for the final
 * callback reference.
 */
typedef void (*sandlock_policy_ud_drop_t)(void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

sandlock_builder_t *sandlock_sandbox_builder_new(void);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_fs_read(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_fs_write(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_fs_deny(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_fs_storage(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` must be a valid pointer. `devices` must point to `len` u32 values (or be null when len == 0).
 */
sandlock_builder_t *sandlock_sandbox_builder_gpu_devices(sandlock_builder_t *b,
                                                         const uint32_t *devices,
                                                         uint32_t len);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_workdir(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_cwd(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_chroot(sandlock_builder_t *b, const char *path);

/**
 * Add a filesystem mount mapping (virtual_path -> host_path).
 *
 * Both paths must be non-empty UTF-8; anything else is ignored and adds no
 * mount (an empty virtual path would match every guest path).
 *
 * # Safety
 * `b`, `virtual_path`, and `host_path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_fs_mount(sandlock_builder_t *b,
                                                      const char *virtual_path,
                                                      const char *host_path);

/**
 * Add a read-only filesystem mount mapping (virtual_path -> host_path).
 *
 * Same mapping as [`sandlock_sandbox_builder_fs_mount`], but a write that
 * resolves to a path under `virtual_path` is denied with `EACCES` (reads,
 * exec and directory listing still go through), and that denial wins over any
 * broader writable rule such as a read-write rootfs granting `/`.
 *
 * The marking is enforced per resolved path, not per inode: a guest that also
 * holds a writable mount on the same host filesystem can hard-link a file out
 * of the read-only mount and then write through the alias. Treat this as a
 * mount-shaped access rule, not as an immutability guarantee for the host
 * files behind it.
 *
 * Mount mappings (and therefore this read-only marking) are only enforced
 * when [`sandlock_sandbox_builder_chroot`] is also set; without a chroot this
 * call has no effect on the guest's filesystem view.
 *
 * Both paths must be non-empty UTF-8; anything else is ignored and adds no
 * mount (an empty virtual path would match every guest path).
 *
 * # Safety
 * `b`, `virtual_path`, and `host_path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_fs_mount_ro(sandlock_builder_t *b,
                                                         const char *virtual_path,
                                                         const char *host_path);

/**
 * Set the COW branch action on successful exit.
 * `action`: 0 = Commit, 1 = Abort, 2 = Keep.
 *
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_on_exit(sandlock_builder_t *b, uint8_t action);

/**
 * Set the COW branch action on error exit.
 * `action`: 0 = Commit, 1 = Abort, 2 = Keep.
 *
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_on_error(sandlock_builder_t *b, uint8_t action);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_max_memory(sandlock_builder_t *b, uint64_t bytes);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_max_disk(sandlock_builder_t *b, uint64_t bytes);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_max_processes(sandlock_builder_t *b, uint32_t n);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_max_cpu(sandlock_builder_t *b, uint8_t pct);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_num_cpus(sandlock_builder_t *b, uint32_t n);

/**
 * # Safety
 * `b` must be a valid builder pointer.  `cores` must point to `len` u32 values.
 */
sandlock_builder_t *sandlock_sandbox_builder_cpu_cores(sandlock_builder_t *b,
                                                       const uint32_t *cores,
                                                       uint32_t len);

/**
 * Append a `--net-allow` endpoint rule. `spec` is `host:port[,port,...]`,
 * `:port`, or `*:port`. Spec is validated when the policy is built;
 * invalid specs surface as a build error.
 *
 * # Safety
 * `b` and `spec` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_net_allow(sandlock_builder_t *b, const char *spec);

/**
 * # Safety
 * `b` and `spec` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_net_deny(sandlock_builder_t *b, const char *spec);

/**
 * Append a `--net-allow-bind` port spec: a comma-separated list of single
 * ports / inclusive `lo-hi` ranges, or the `"*"` wildcard to allow binding
 * any TCP port. Spec is validated when the policy is built; invalid specs
 * (including `"*"` mixed with port lists) surface as a build error.
 *
 * # Safety
 * `b` and `spec` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_net_allow_bind(sandlock_builder_t *b,
                                                            const char *spec);

/**
 * Append a `--net-deny-bind` port spec: a comma-separated list of single
 * ports / inclusive `lo-hi` ranges. The `"*"` wildcard is not accepted on
 * the deny side. Spec is validated when the policy is built; invalid specs
 * surface as a build error.
 *
 * # Safety
 * `b` and `spec` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_net_deny_bind(sandlock_builder_t *b, const char *spec);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_port_remap(sandlock_builder_t *b, bool v);

/**
 * Run the sandboxed process as `uid`/`gid` via a single-entry user namespace
 * map (no host privilege required).
 *
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_user(sandlock_builder_t *b,
                                                  uint32_t uid,
                                                  uint32_t gid);

/**
 * # Safety
 * `b` and `rule` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_allow(sandlock_builder_t *b, const char *rule);

/**
 * # Safety
 * `b` and `rule` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_deny(sandlock_builder_t *b, const char *rule);

/**
 * # Safety
 * `b` must be a valid pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_port(sandlock_builder_t *b, uint16_t port);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_ca(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_key(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_inject_ca(sandlock_builder_t *b,
                                                            const char *path);

/**
 * # Safety
 * `b` and `path` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_http_ca_out(sandlock_builder_t *b, const char *path);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_random_seed(sandlock_builder_t *b, uint64_t seed);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_clean_env(sandlock_builder_t *b, bool v);

/**
 * # Safety
 * `b`, `key`, and `value` must be valid pointers.
 */
sandlock_builder_t *sandlock_sandbox_builder_env_var(sandlock_builder_t *b,
                                                     const char *key,
                                                     const char *value);

/**
 * # Safety
 * `b` must be a valid builder pointer. `epoch_secs` is seconds since UNIX epoch.
 */
sandlock_builder_t *sandlock_sandbox_builder_time_start(sandlock_builder_t *b, uint64_t epoch_secs);

/**
 * # Safety
 * `b` must be a valid builder pointer. `names` is a comma-separated NUL-terminated string.
 */
sandlock_builder_t *sandlock_sandbox_builder_extra_deny_syscalls(sandlock_builder_t *b,
                                                                 const char *names);

/**
 * # Safety
 * `b` must be a valid builder pointer. `names` is a comma-separated NUL-terminated string.
 */
sandlock_builder_t *sandlock_sandbox_builder_extra_allow_syscalls(sandlock_builder_t *b,
                                                                  const char *names);

/**
 * Resolve a syscall name (e.g. `"openat"`) to its kernel syscall
 * number for the host architecture.
 *
 * Intended for filling a `sandlock_handler_registration_t`'s
 * `syscall_nr` without hard-coding architecture-specific numbers.
 *
 * Returns the syscall number on success, or `-1` if `name` is NULL,
 * is not valid UTF-8, or names a syscall sandlock does not know. The
 * resolvable set covers the syscalls sandlock filters or supervises;
 * syscalls outside that set (e.g. `getpid`) return `-1` and must be
 * registered by raw number.
 *
 * # Safety
 * `name` must be NULL or a valid NUL-terminated C string.
 */
int64_t sandlock_syscall_nr(const char *name);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_max_open_files(sandlock_builder_t *b, unsigned int n);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_no_randomize_memory(sandlock_builder_t *b, bool v);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_no_huge_pages(sandlock_builder_t *b, bool v);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_no_coredump(sandlock_builder_t *b, bool v);

/**
 * # Safety
 * `b` must be a valid builder pointer.
 */
sandlock_builder_t *sandlock_sandbox_builder_deterministic_dirs(sandlock_builder_t *b, bool v);

/**
 * Per-protection minimum Landlock ABI version required by the host
 * kernel for this protection to be available.
 *
 * Returns `0` for any `protection` value that is not a known
 * discriminant — `0` is below every real `min_abi()` (which start at
 * `2`), so callers can use it as an "unknown protection" sentinel
 * without colliding with a valid version number.
 */
uint32_t sandlock_protection_min_abi(uint32_t protection);

/**
 * Mark `protection` as degradable on the builder: enforced when the
 * host kernel supports it, silently skipped otherwise.
 *
 * Returns the (possibly relocated) builder pointer, mirroring the
 * move-semantics convention used by every other
 * `sandlock_sandbox_builder_*` setter. A null `b` is returned
 * unchanged. An unknown `protection` discriminant is treated as a
 * no-op: the builder is returned untouched.
 *
 * # Safety
 * `b` must be a valid builder pointer returned by
 * `sandlock_sandbox_builder_new` (or a previous builder setter) and
 * not freed.
 */
sandlock_builder_t *sandlock_sandbox_builder_allow_degraded(sandlock_builder_t *b,
                                                            uint32_t protection);

/**
 * Mark `protection` as disabled on the builder: never enforced, even
 * on a host kernel that supports it.
 *
 * Returns the (possibly relocated) builder pointer, mirroring the
 * move-semantics convention used by every other
 * `sandlock_sandbox_builder_*` setter. A null `b` is returned
 * unchanged. An unknown `protection` discriminant is treated as a
 * no-op: the builder is returned untouched.
 *
 * # Safety
 * `b` must be a valid builder pointer returned by
 * `sandlock_sandbox_builder_new` (or a previous builder setter) and
 * not freed.
 */
sandlock_builder_t *sandlock_sandbox_builder_disable(sandlock_builder_t *b, uint32_t protection);

/**
 * Consume the builder and produce a policy.
 * On success, `*err` is 0 and a non-null policy pointer is returned.
 * On failure, `*err` is -1, null is returned, and `*err_msg` (if
 * non-null) is set to a heap-allocated C string describing the
 * error. The caller must release that string with
 * [`sandlock_string_free`]. Pass `null` for `err_msg` to discard.
 *
 * # Safety
 * `b` must be a valid builder pointer. `err` and `err_msg` may both
 * be null. When `err_msg` is non-null, it must point to writable
 * storage for one `*mut c_char`.
 */
sandlock_sandbox_t *sandlock_sandbox_build(sandlock_builder_t *b, int *err, char **err_msg);

/**
 * # Safety
 * `p` must be null or a valid pointer from `sandlock_sandbox_build`.
 */
void sandlock_sandbox_free(sandlock_sandbox_t *p);

/**
 * Confine the calling process with Landlock filesystem rules.
 * This is irreversible. Returns 0 on success, -1 on error.
 *
 * # Safety
 * `policy` must be a valid policy pointer.
 */
int sandlock_confine(const sandlock_sandbox_t *policy);

/**
 * Run a command with captured stdout/stderr. Returns a result handle.
 *
 * # Safety
 * `policy` must be a valid policy pointer. `name` may be NULL to
 * auto-generate a sandbox name, or a valid NUL-terminated string.
 * `argv` must point to `argc` C strings.
 */
sandlock_result_t *sandlock_run(const sandlock_sandbox_t *policy,
                                const char *name,
                                const char *const *argv,
                                unsigned int argc);

sandlock_handle_t *sandlock_create(const sandlock_sandbox_t *policy,
                                   const char *name,
                                   const char *const *argv,
                                   unsigned int argc);

/**
 * Create a sandbox handle for immediate start+wait use on the calling
 * FFI thread. Unlike `sandlock_create`, this uses the thread-local
 * `current_thread` runtime and does not create Tokio worker threads.
 *
 * This is intended for blocking one-shot wrappers that call
 * `sandlock_start` and `sandlock_handle_wait*` immediately from the
 * same thread. Long-lived handles should use `sandlock_create` so the
 * supervisor keeps progressing between FFI calls.
 *
 * # Safety
 * Same constraints as `sandlock_create`.
 */
sandlock_handle_t *sandlock_create_for_run(const sandlock_sandbox_t *policy,
                                           const char *name,
                                           const char *const *argv,
                                           unsigned int argc);

/**
 * Spawn a confined process with per-stream stdio wiring and return a live
 * handle (the streaming counterpart of `sandlock_create` + `sandlock_start`).
 *
 * `stdin_mode`/`stdout_mode`/`stderr_mode` are `StdioMode` discriminants
 * (0=inherit, 1=piped, 2=null). For each stream set to *piped*, the matching
 * `out_*_fd` receives an owned fd the caller must `close()`; for inherit/null
 * it receives -1. Pass null for an `out_*_fd` to discard that fd (it is closed
 * rather than leaked). Returns null on error (unknown mode, build/fork
 * failure) with every `out_*_fd` left -1.
 *
 * The handle uses a multi-threaded runtime so the seccomp supervisor keeps
 * pumping while the caller does blocking IO on the returned fds. Wait for the
 * process with `sandlock_handle_wait`, terminate with `sandlock_handle_kill`,
 * and release with `sandlock_handle_free`.
 *
 * Deadlock warning: a piped fd is yours once returned — `close()` a piped
 * `out_stdin_fd` *before* `sandlock_handle_wait`, or a child that reads to EOF
 * (e.g. `cat`) never exits and the wait blocks forever. Likewise drain a piped
 * `out_stdout_fd`/`out_stderr_fd` before waiting: a child that fills the pipe
 * buffer blocks on write and never reaches exit.
 *
 * # Safety
 * As `sandlock_create`; `out_*_fd` must each be null or a valid `*mut c_int`.
 */
sandlock_handle_t *sandlock_popen(const sandlock_sandbox_t *policy,
                                  const char *name,
                                  const char *const *argv,
                                  unsigned int argc,
                                  uint32_t stdin_mode,
                                  uint32_t stdout_mode,
                                  uint32_t stderr_mode,
                                  int *out_stdin_fd,
                                  int *out_stdout_fd,
                                  int *out_stderr_fd);

/**
 * Release a previously `sandlock_create`d child to execve. Returns 0 on
 * success, -1 on error.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create`.
 */
int sandlock_start(sandlock_handle_t *h);

/**
 * Get the child PID. Returns 0 if not available.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create`.
 */
int32_t sandlock_handle_pid(const sandlock_handle_t *h);

/**
 * Send SIGKILL to the handle's entire process group. Idempotent: a process
 * that already exited is not an error. Returns 0 on success, -1 on error.
 * The handle remains valid; call `sandlock_handle_wait` to collect the exit
 * status and `sandlock_handle_free` to release it.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create` / `sandlock_popen`.
 */
int sandlock_handle_kill(sandlock_handle_t *h);

/**
 * Wait for the sandbox to exit. Returns a result handle with stdout/stderr.
 *
 * For a `sandlock_popen` handle, close a piped `out_stdin_fd` and drain any
 * piped `out_stdout_fd`/`out_stderr_fd` *before* calling this, or a child that
 * reads to EOF or fills a pipe buffer never exits and this blocks forever.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create` / `sandlock_popen`.
 */
sandlock_result_t *sandlock_handle_wait(sandlock_handle_t *h);

/**
 * Wait for the sandbox to exit with a timeout in milliseconds.
 * Returns a result handle, or null on error. On timeout the sandbox is
 * killed and a result with `ExitStatus::Timeout` is returned.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create`.
 */
sandlock_result_t *sandlock_handle_wait_timeout(sandlock_handle_t *h, uint64_t timeout_ms);

/**
 * Get port mappings as a JSON string (e.g. `{"80":9001,"443":9002}`).
 * Returns a C string that must be freed with `sandlock_string_free`.
 * Returns null if port_remap is not active or no ports are mapped.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create`.
 */
char *sandlock_handle_port_mappings(const sandlock_handle_t *h);

/**
 * Free a sandbox handle. Kills the process if still running.
 *
 * # Safety
 * `h` must be null or a valid handle from `sandlock_create` / `sandlock_popen`.
 */
void sandlock_handle_free(sandlock_handle_t *h);

/**
 * Run a command with inherited stdio (interactive). Returns exit code.
 *
 * # Safety
 * `policy` must be a valid policy pointer. `name` may be NULL to
 * auto-generate a sandbox name, or a valid NUL-terminated string.
 * `argv` must point to `argc` C strings.
 */
int sandlock_run_interactive(const sandlock_sandbox_t *policy,
                             const char *name,
                             const char *const *argv,
                             unsigned int argc);

/**
 * # Safety
 * `r` must be null or a valid result pointer.
 */
int sandlock_result_exit_code(const sandlock_result_t *r);

/**
 * Terminating reason (normal exit / signal / kill / timeout). Pair with
 * `sandlock_result_exit_code` (for `EXITED`) and `sandlock_result_signal`
 * (for `SIGNALED`). Returns `KILLED` for a null result.
 *
 * # Safety
 * `r` must be null or a valid result pointer.
 */
sandlock_exit_reason sandlock_result_reason(const sandlock_result_t *r);

/**
 * Signal number for a `SIGNALED` result, or `-1` for any other reason
 * (including a null result).
 *
 * # Safety
 * `r` must be null or a valid result pointer.
 */
int sandlock_result_signal(const sandlock_result_t *r);

/**
 * # Safety
 * `r` must be null or a valid result pointer.
 */
bool sandlock_result_success(const sandlock_result_t *r);

/**
 * Get captured stdout. Returns a malloc'd NUL-terminated string.
 * Caller must free with `sandlock_string_free`. Returns null if no capture.
 *
 * # Safety
 * `r` must be null or a valid result pointer.
 */
char *sandlock_result_stdout(const sandlock_result_t *r);

/**
 * Get captured stderr. Same semantics as `sandlock_result_stdout`.
 *
 * # Safety
 * `r` must be null or a valid result pointer.
 */
char *sandlock_result_stderr(const sandlock_result_t *r);

/**
 * Get captured stdout as raw bytes. Writes length to `*len`.
 * Returns pointer to internal buffer (valid until result is freed). Null if no capture.
 *
 * # Safety
 * `r` must be a valid result pointer. `len` must be a valid pointer.
 */
const uint8_t *sandlock_result_stdout_bytes(const sandlock_result_t *r, uintptr_t *len);

/**
 * Get captured stderr as raw bytes.
 *
 * # Safety
 * `r` must be a valid result pointer. `len` must be a valid pointer.
 */
const uint8_t *sandlock_result_stderr_bytes(const sandlock_result_t *r, uintptr_t *len);

/**
 * # Safety
 * `r` must be null or a valid pointer from `sandlock_run`.
 */
void sandlock_result_free(sandlock_result_t *r);

/**
 * Free a string returned by `sandlock_result_stdout` or `sandlock_result_stderr`.
 *
 * # Safety
 * `s` must be null or a pointer from a `sandlock_result_std*` function.
 */
void sandlock_string_free(char *s);

/**
 * Run a command in dry-run mode with captured stdout/stderr.
 *
 * # Safety
 * `policy` must be a valid policy pointer. `name` may be NULL to
 * auto-generate a sandbox name, or a valid NUL-terminated string.
 * `argv` must point to `argc` C strings.
 */
sandlock_dry_run_result_t *sandlock_dry_run(const sandlock_sandbox_t *policy,
                                            const char *name,
                                            const char *const *argv,
                                            unsigned int argc);

/**
 * Get the exit code from a dry-run result.
 *
 * # Safety
 * `r` must be a valid dry-run result pointer.
 */
int sandlock_dry_run_result_exit_code(const sandlock_dry_run_result_t *r);

/**
 * Terminating reason of a dry-run result (parity with
 * `sandlock_result_reason`). Returns `KILLED` for a null result.
 *
 * # Safety
 * `r` must be null or a valid dry-run result pointer.
 */
sandlock_exit_reason sandlock_dry_run_result_reason(const sandlock_dry_run_result_t *r);

/**
 * Signal number for a `SIGNALED` dry-run result, or `-1` otherwise (parity
 * with `sandlock_result_signal`).
 *
 * # Safety
 * `r` must be null or a valid dry-run result pointer.
 */
int sandlock_dry_run_result_signal(const sandlock_dry_run_result_t *r);

/**
 * Check if the dry-run result indicates success.
 *
 * # Safety
 * `r` must be a valid dry-run result pointer.
 */
bool sandlock_dry_run_result_success(const sandlock_dry_run_result_t *r);

/**
 * Get captured stdout bytes from a dry-run result.
 *
 * # Safety
 * `r` must be a valid dry-run result pointer. `len` must be a valid pointer.
 */
const uint8_t *sandlock_dry_run_result_stdout_bytes(const sandlock_dry_run_result_t *r,
                                                    uintptr_t *len);

/**
 * Get captured stderr bytes from a dry-run result.
 *
 * # Safety
 * `r` must be a valid dry-run result pointer. `len` must be a valid pointer.
 */
const uint8_t *sandlock_dry_run_result_stderr_bytes(const sandlock_dry_run_result_t *r,
                                                    uintptr_t *len);

/**
 * Get the number of filesystem changes in a dry-run result.
 *
 * # Safety
 * `r` must be a valid dry-run result pointer.
 */
uintptr_t sandlock_dry_run_result_changes_len(const sandlock_dry_run_result_t *r);

/**
 * Get the kind of the i-th change: 'A' (added), 'M' (modified), 'D' (deleted).
 *
 * # Safety
 * `r` must be a valid dry-run result pointer. `i` must be < changes_len.
 */
char sandlock_dry_run_result_change_kind(const sandlock_dry_run_result_t *r, uintptr_t i);

/**
 * Get the path of the i-th change as a C string. Caller must free with `sandlock_string_free`.
 *
 * # Safety
 * `r` must be a valid dry-run result pointer. `i` must be < changes_len.
 */
char *sandlock_dry_run_result_change_path(const sandlock_dry_run_result_t *r, uintptr_t i);

/**
 * Free a dry-run result.
 *
 * # Safety
 * `r` must be null or a valid dry-run result pointer.
 */
void sandlock_dry_run_result_free(sandlock_dry_run_result_t *r);

/**
 * Create a new empty pipeline.
 */
sandlock_pipeline_t *sandlock_pipeline_new(void);

/**
 * Add a stage to the pipeline. The policy is cloned; the caller retains ownership.
 *
 * # Safety
 * `pipe` must be a valid pipeline pointer. `policy` must be a valid policy pointer.
 * `argv` must point to `argc` C strings.
 */
void sandlock_pipeline_add_stage(sandlock_pipeline_t *pipe,
                                 const sandlock_sandbox_t *policy,
                                 const char *const *argv,
                                 unsigned int argc);

/**
 * Run the pipeline. Returns a result handle (last stage's output).
 * `timeout_ms` is the total timeout in milliseconds (0 = no timeout).
 *
 * # Safety
 * `pipe` is consumed and freed by this call. Do not use it after.
 */
sandlock_result_t *sandlock_pipeline_run(sandlock_pipeline_t *pipe, uint64_t timeout_ms);

/**
 * Free a pipeline without running it.
 *
 * # Safety
 * `pipe` must be null or a valid pipeline pointer.
 */
void sandlock_pipeline_free(sandlock_pipeline_t *pipe);

/**
 * Create a new empty gather.
 */
sandlock_gather_t *sandlock_gather_new(void);

/**
 * Add a named source to the gather.
 *
 * # Safety
 * All pointers must be valid. `name` must be a NUL-terminated C string.
 */
void sandlock_gather_add_source(sandlock_gather_t *g,
                                const char *name,
                                const sandlock_sandbox_t *policy,
                                const char *const *argv,
                                unsigned int argc);

/**
 * Set the consumer stage for the gather.
 *
 * # Safety
 * All pointers must be valid.
 */
void sandlock_gather_set_consumer(sandlock_gather_t *g,
                                  const sandlock_sandbox_t *policy,
                                  const char *const *argv,
                                  unsigned int argc);

/**
 * Run the gather. Consumes the gather handle.
 *
 * # Safety
 * `g` must be a valid gather pointer.
 */
sandlock_result_t *sandlock_gather_run(sandlock_gather_t *g, uint64_t timeout_ms);

/**
 * Free a gather without running it.
 *
 * # Safety
 * `g` must be null or a valid gather pointer.
 */
void sandlock_gather_free(sandlock_gather_t *g);

/**
 * Set a policy callback on the builder.
 *
 * # Safety
 * `b` must be a valid builder pointer. `cb` must be a valid function pointer
 * that remains valid for the lifetime of the sandbox callback.
 * `user_data` is opaque to Rust and is passed back to every callback
 * invocation. It must remain valid and be safe to access from the policy-fn
 * worker thread until `user_data_drop` is invoked. `user_data_drop = None` is
 * legal when no cleanup is needed; if provided, it must not unwind.
 */
sandlock_builder_t *sandlock_sandbox_builder_policy_fn(sandlock_builder_t *b,
                                                       sandlock_policy_fn_t cb,
                                                       void *user_data,
                                                       void (*user_data_drop)(void *user_data));

/**
 * Restrict network to the given IPs. Permanent — cannot grant back.
 *
 * # Safety
 * `ctx` must be a valid context pointer from inside a policy callback.
 * `ips` must point to `count` valid C strings.
 */
void sandlock_ctx_restrict_network(sandlock_ctx_t *ctx, const char *const *ips, uint32_t count);

/**
 * Grant network IPs (within ceiling). Fails silently if restricted.
 *
 * # Safety
 * Same as `sandlock_ctx_restrict_network`.
 */
void sandlock_ctx_grant_network(sandlock_ctx_t *ctx, const char *const *ips, uint32_t count);

/**
 * Restrict max memory. Permanent.
 *
 * # Safety
 * `ctx` must be a valid context pointer.
 */
void sandlock_ctx_restrict_max_memory(sandlock_ctx_t *ctx, uint64_t bytes);

/**
 * Restrict max processes. Permanent.
 *
 * # Safety
 * `ctx` must be a valid context pointer.
 */
void sandlock_ctx_restrict_max_processes(sandlock_ctx_t *ctx, uint32_t n);

/**
 * Restrict network for a specific PID.
 *
 * # Safety
 * `ctx` must be a valid context pointer. `ips` must point to `count` C strings.
 */
void sandlock_ctx_restrict_pid_network(sandlock_ctx_t *ctx,
                                       uint32_t pid,
                                       const char *const *ips,
                                       uint32_t count);

/**
 * Deny access to a path dynamically (checked on openat).
 *
 * # Safety
 * `ctx` must be a valid context pointer. `path` must be a valid C string.
 */
void sandlock_ctx_deny_path(sandlock_ctx_t *ctx, const char *path);

/**
 * Remove a previously denied path.
 *
 * # Safety
 * `ctx` must be a valid context pointer. `path` must be a valid C string.
 */
void sandlock_ctx_allow_path(sandlock_ctx_t *ctx, const char *path);

/**
 * Create a sandbox with init/work functions for COW forking.
 *
 * # Safety
 * `policy` must be valid. `name` may be NULL to auto-generate a sandbox
 * name, or a valid NUL-terminated string. `init_fn` and `work_fn` must
 * be valid function pointers.
 */
sandlock_t *sandlock_new_with_fns(const sandlock_sandbox_t *policy,
                                  const char *name,
                                  sandlock_init_fn_t init_fn,
                                  sandlock_work_fn_t work_fn);

/**
 * Fork N COW clones. Returns a fork result handle (NULL on error).
 *
 * # Safety
 * `sb` must be a valid sandbox pointer from `sandlock_new_with_fns`.
 */
sandlock_fork_result_t *sandlock_fork(sandlock_t *sb, uint32_t n);

/**
 * Get the number of clones.
 */
uint32_t sandlock_fork_result_count(const sandlock_fork_result_t *r);

/**
 * Get a clone's PID.
 */
int32_t sandlock_fork_result_pid(const sandlock_fork_result_t *r, uint32_t index);

/**
 * Reduce: read all clone stdout pipes, feed to reducer stdin, return result.
 *
 * # Safety
 * `fork_result` is consumed. `policy` and `argv` must be valid. `name`
 * may be NULL to auto-generate a sandbox name, or a valid
 * NUL-terminated string.
 */
sandlock_result_t *sandlock_reduce(sandlock_fork_result_t *fork_result,
                                   const sandlock_sandbox_t *policy,
                                   const char *name,
                                   const char *const *argv,
                                   unsigned int argc);

/**
 * Free a fork result without reducing.
 */
void sandlock_fork_result_free(sandlock_fork_result_t *r);

/**
 * Wait for the sandbox template to exit. Returns exit code.
 *
 * # Safety
 * `sb` must be a valid sandbox pointer.
 */
int sandlock_wait(sandlock_t *sb);

/**
 * Free a Sandbox handle created by `sandlock_new_with_fns`.
 *
 * # Safety
 * `sb` must be null or a valid Sandbox pointer.
 */
void sandlock_sandbox_fns_free(sandlock_t *sb);

/**
 * Capture a checkpoint from a live sandbox handle.
 * The sandbox is frozen (SIGSTOP + fork-hold), state is captured via ptrace,
 * then thawed. Returns NULL on error.
 *
 * # Safety
 * `h` must be a valid handle from `sandlock_create`.
 */
sandlock_checkpoint_t *sandlock_handle_checkpoint(sandlock_handle_t *h);

/**
 * Save a checkpoint to a directory (human-readable JSON + binary layout).
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 * `cp` must be a valid checkpoint pointer. `dir` must be a valid C string path.
 */
int sandlock_checkpoint_save(const sandlock_checkpoint_t *cp, const char *dir);

/**
 * Load a checkpoint from a directory.
 * Returns NULL on error.
 *
 * # Safety
 * `dir` must be a valid C string path to a checkpoint directory.
 */
sandlock_checkpoint_t *sandlock_checkpoint_load(const char *dir);

/**
 * Set the checkpoint name.
 *
 * # Safety
 * `cp` must be a valid checkpoint pointer. `name` must be a valid C string.
 */
void sandlock_checkpoint_set_name(sandlock_checkpoint_t *cp, const char *name);

/**
 * Get the checkpoint name. Returns a malloc'd C string; free with `sandlock_string_free`.
 *
 * # Safety
 * `cp` must be a valid checkpoint pointer.
 */
char *sandlock_checkpoint_name(const sandlock_checkpoint_t *cp);

/**
 * Set optional app-level state bytes on the checkpoint.
 *
 * # Safety
 * `cp` must be valid. `data` must point to `len` bytes, or be NULL to clear.
 */
void sandlock_checkpoint_set_app_state(sandlock_checkpoint_t *cp,
                                       const uint8_t *data,
                                       uintptr_t len);

/**
 * Get app-level state bytes. Returns pointer to internal buffer (valid until
 * checkpoint is freed). Writes length to `*len`. Returns NULL if no app state.
 *
 * # Safety
 * `cp` must be a valid checkpoint pointer. `len` must be a valid pointer.
 */
const uint8_t *sandlock_checkpoint_app_state(const sandlock_checkpoint_t *cp, uintptr_t *len);

/**
 * Free a checkpoint handle.
 *
 * # Safety
 * `cp` must be null or a valid checkpoint pointer.
 */
void sandlock_checkpoint_free(sandlock_checkpoint_t *cp);

/**
 * Restore a checkpoint into a fresh, fully-sandboxed process.
 *
 * Builds a new sandbox from `policy` (with the optional `name`, as in
 * `sandlock_create`) and injects the checkpoint image over a parked child,
 * which resumes at the saved program counter under the full confinement.
 * Returns a live handle: the process is already running, so do NOT call
 * `sandlock_start` on it; manage it with `sandlock_handle_kill` /
 * `sandlock_handle_wait` / `sandlock_handle_free` as usual. Returns NULL on
 * error (any half-built child is reaped before returning).
 *
 * Fds that could not be transparently restored (sockets, pipes, memfds,
 * pseudo-filesystem paths) are recorded on the handle; enumerate them with
 * `sandlock_handle_restore_skipped_len` / `_fd` / `_path`.
 *
 * x86_64 restore engine only. Transparent restore currently holds for
 * vDSO-free programs; see `Sandbox::restore_interactive` in sandlock-core.
 *
 * # Safety
 * `policy` must be a valid policy pointer and `cp` a valid checkpoint
 * pointer. `name` may be NULL to auto-generate a sandbox name, or a valid
 * NUL-terminated string.
 */
sandlock_handle_t *sandlock_restore_interactive(const sandlock_sandbox_t *policy,
                                                const char *name,
                                                const sandlock_checkpoint_t *cp);

/**
 * Number of fds the restore that produced this handle could not
 * transparently recreate. 0 for a NULL handle or a handle not produced by
 * `sandlock_restore_interactive`.
 *
 * # Safety
 * `h` must be null or a valid handle.
 */
uintptr_t sandlock_handle_restore_skipped_len(const sandlock_handle_t *h);

/**
 * The fd number of the i-th skipped entry (its fd in the checkpointed
 * process). Returns -1 if `h` is NULL or `i` is out of range.
 *
 * # Safety
 * `h` must be null or a valid handle.
 */
int sandlock_handle_restore_skipped_fd(const sandlock_handle_t *h, uintptr_t i);

/**
 * The resource path of the i-th skipped entry (e.g. `pipe:[12345]`).
 * Returns a malloc'd C string to free with `sandlock_string_free`, or NULL
 * if `h` is NULL or `i` is out of range.
 *
 * # Safety
 * `h` must be null or a valid handle.
 */
char *sandlock_handle_restore_skipped_path(const sandlock_handle_t *h, uintptr_t i);

/**
 * Query the Landlock ABI version supported by the running kernel.
 * Returns the ABI version (>= 1), or -1 if Landlock is unavailable.
 */
int sandlock_landlock_abi_version(void);

/**
 * Return the minimum Landlock ABI version required by this build of sandlock.
 */
int sandlock_min_landlock_abi(void);

/**
 * Read up to `max_len-1` bytes of a NUL-terminated string at `addr` from the
 * traced child. On success the destination buffer is NUL-terminated and
 * `*out_len` holds the byte count copied (excluding the NUL); returns 0.
 * On failure returns -1 and leaves `*out_len` untouched. `max_len` must be
 * at least 1 to fit the NUL terminator.
 *
 * # Safety
 * `handle` must point to a live `sandlock_mem_handle_t` provided by the
 * supervisor; `buf` must be writable for `max_len` bytes; `out_len` must
 * be a valid `size_t*`.
 */
int32_t sandlock_mem_read_cstr(const sandlock_mem_handle_t *handle,
                               uint64_t addr,
                               uint8_t *buf,
                               uintptr_t max_len,
                               uintptr_t *out_len);

/**
 * Raw byte read at `addr` of exactly `len` bytes. Writes byte count
 * actually read to `*out_len`. Returns 0 on success, -1 on failure.
 *
 * # Safety
 * Same constraints as `sandlock_mem_read_cstr`.
 */
int32_t sandlock_mem_read(const sandlock_mem_handle_t *handle,
                          uint64_t addr,
                          uint8_t *buf,
                          uintptr_t len,
                          uintptr_t *out_len);

/**
 * Write `len` bytes from `buf` into the child at `addr`. Returns 0 on
 * success, -1 on failure.
 *
 * # Safety
 * Same constraints as `sandlock_mem_read_cstr`; `buf` must be readable
 * for `len` bytes.
 */
int32_t sandlock_mem_write(const sandlock_mem_handle_t *handle,
                           uint64_t addr,
                           const uint8_t *buf,
                           uintptr_t len);

/**
 * Mark the action as `Continue` (let the syscall proceed unchanged).
 *
 * # Safety
 * `out` must be a valid pointer to a `sandlock_action_out_t` writable
 * for the duration of the call, or null (in which case the call is a
 * no-op).
 */
void sandlock_action_set_continue(sandlock_action_out_t *out);

/**
 * Fail the syscall with `errno`.
 *
 * # Safety
 * Same constraints as `sandlock_action_set_continue`.
 */
void sandlock_action_set_errno(sandlock_action_out_t *out, int32_t errno_value);

/**
 * Return a specific value from the syscall without entering the kernel.
 *
 * # Safety
 * Same constraints as `sandlock_action_set_continue`.
 */
void sandlock_action_set_return_value(sandlock_action_out_t *out, int64_t value);

/**
 * Inject the supervisor-side fd `srcfd` into the traced child as a new
 * fd (number chosen by the kernel via `SECCOMP_IOCTL_NOTIF_ADDFD`).
 *
 * Note: ownership of `srcfd` transfers from the C caller to the
 * supervisor only when the resulting action is actually dispatched.
 * If the C caller subsequently calls a different setter on the same
 * `sandlock_action_out_t` (overwriting the kind tag before the
 * supervisor reads it), `srcfd` is NOT closed and leaks. Pick one
 * setter per action.
 *
 * # Safety
 * Same constraints as `sandlock_action_set_continue`; `srcfd` must be
 * a valid open fd in the supervisor process at the moment of the
 * supervisor's dispatch.
 */
void sandlock_action_set_inject_fd_send(sandlock_action_out_t *out,
                                        int srcfd,
                                        uint32_t newfd_flags);

/**
 * Inject `len` bytes from `data` into the child as the syscall's returned
 * fd, backed by an in-memory file created by the supervisor. The bytes are
 * copied immediately, so `data` need not outlive the call.
 *
 * `flags` is a bitmask of `SANDLOCK_INJECT_*`. With `flags == 0` the memfd is
 * sealed read-only and the child-side fd is `O_CLOEXEC` — the safe default
 * for synthetic file content (secrets, virtual files, fetched objects). On
 * allocation failure the action is set to `Errno(EIO)`, so the callback's
 * one-setter contract still holds and the child gets a definite response.
 *
 * Unlike [`sandlock_action_set_inject_fd_send`], the caller owns no fd here:
 * the supervisor creates, populates, and (on dispatch) closes the memfd.
 *
 * # Safety
 * `out` follows the same constraints as `sandlock_action_set_continue`.
 * `data` must point to at least `len` readable bytes, or be null when
 * `len == 0`.
 */
void sandlock_action_set_inject_bytes(sandlock_action_out_t *out,
                                      const uint8_t *data,
                                      uintptr_t len,
                                      uint32_t flags);

/**
 * Hold the syscall pending until the supervisor explicitly releases it.
 *
 * # Safety
 * Same constraints as `sandlock_action_set_continue`.
 */
void sandlock_action_set_hold(sandlock_action_out_t *out);

/**
 * Kill the target with signal `sig`. Pass `pgid > 0` to target an
 * explicit process group; `pgid == 0` is a sentinel — the supervisor
 * substitutes the child process group id resolved via `getpgid(pid)`
 * on the notification's pid.
 *
 * # Safety
 * Same constraints as `sandlock_action_set_continue`.
 */
void sandlock_action_set_kill(sandlock_action_out_t *out, int32_t sig, int32_t pgid);

/**
 * Allocate a handler container. `handler_fn` must be non-null; passing
 * `ud_drop = None` is legal when `ud` does not require cleanup.
 *
 * # Safety
 * `ud` is opaque to Rust — the caller guarantees that the pointer
 * remains valid until either (a) `sandlock_handler_free` is called or
 * (b) the supervisor takes ownership via `sandlock_run_with_handlers`
 * and the run completes.
 * If `on_exception` does not match a defined `sandlock_exception_policy_t`
 * discriminant (0, 1, 2, or 3), the call returns null and no allocation occurs.
 */
sandlock_handler_t *sandlock_handler_new(int32_t (*handler_fn)(void *ud,
                                                               const sandlock_notif_data_t *notif,
                                                               sandlock_mem_handle_t *mem,
                                                               sandlock_action_out_t *out),
                                         void *ud,
                                         void (*ud_drop)(void *ud),
                                         uint32_t on_exception);

/**
 * Mark a handler as deferred: the supervisor will run its callback off the
 * notification loop so a slow callback does not block other trapped
 * syscalls. Must be called before the handler is registered with a run.
 *
 * A deferred handler makes a *terminal* decision: deferral short-circuits
 * the handler chain, so if a deferred handler would `Continue` and other
 * user handlers are registered on the same syscall, those later handlers do
 * not run. Builtins always run first regardless. Deferral is refused at
 * dispatch time for syscalls whose Continue path needs the execve
 * argv-safety freeze (`execve`/`execveat`) or fork creation-tracking.
 *
 * # Safety
 * `h` must be a non-null pointer returned by `sandlock_handler_new` that has
 * not yet been registered with a run or freed.
 */
void sandlock_handler_set_deferred(sandlock_handler_t *h, bool deferred);

/**
 * Free a handler container that has *not* been registered with a
 * sandbox. After successful registration the supervisor owns the
 * handler; calling this on a registered handler is undefined behaviour
 * (the supervisor's later free would double-free).
 *
 * The ABI is `extern "C-unwind"` rather than plain `extern "C"` so a
 * panic propagated from a Rust-side `ud_drop` (declared as
 * [`sandlock_handler_ud_drop_t`], itself `extern "C-unwind"`) unwinds
 * the caller rather than aborting the process. Pure-C callers see no
 * difference (C has no unwinding).
 *
 * # Safety
 * `h` must be either null or a pointer previously returned by
 * `sandlock_handler_new` that has not yet been registered with the
 * supervisor and has not already been freed.
 */
void sandlock_handler_free(sandlock_handler_t *h);

/**
 * Run the policy with C handlers. Returns NULL on failure.
 *
 * `name` may be NULL to auto-generate `sandbox-{pid}`, or a valid
 * NUL-terminated UTF-8 C string; the placement mirrors the existing
 * `sandlock_run` entry point in `lib.rs`.
 *
 * Declared `extern "C-unwind"` because the handler containers reach
 * this entry point as part of the registration array and their
 * user-supplied `ud_drop` may panic when the supervisor frees them
 * (either during a normal Box-drop or on the early-return cleanup in
 * `release_registrations`). Unwinding across an `extern "C"` boundary
 * is undefined behaviour and aborts the process under modern
 * rustc — `extern "C-unwind"` is the only legal way to let such a
 * panic propagate to the caller, who can then decide whether to
 * catch it.
 *
 * # Safety
 * All pointer arguments must be valid for their documented lifetimes:
 * `policy` must come from `sandlock_sandbox_build`, `argv` must be a
 * readable array of `argc` NUL-terminated strings, and each handler
 * pointer must come from `sandlock_handler_new` and must not be reused
 * after this call (ownership transfers in).
 */
sandlock_result_t *sandlock_run_with_handlers(const sandlock_sandbox_t *policy,
                                              const char *name,
                                              const char *const *argv,
                                              uint32_t argc,
                                              const sandlock_handler_registration_t *registrations,
                                              uintptr_t nregistrations);

/**
 * Interactive-stdio variant of `sandlock_run_with_handlers`.
 *
 * `name` follows the same convention as `sandlock_run_with_handlers`.
 * The `extern "C-unwind"` declaration carries the same rationale: a
 * panicking `ud_drop` must be able to unwind out of this entry point
 * without process abort.
 *
 * # Safety
 * Same constraints as `sandlock_run_with_handlers`.
 */
sandlock_result_t *sandlock_run_interactive_with_handlers(const sandlock_sandbox_t *policy,
                                                          const char *name,
                                                          const char *const *argv,
                                                          uint32_t argc,
                                                          const sandlock_handler_registration_t *registrations,
                                                          uintptr_t nregistrations);

/**
 * Create an empty transaction.
 *
 * Free it with [`sandlock_txn_free`] unless it is consumed by a run.
 */
sandlock_txn_t *sandlock_txn_new(void);

/**
 * Append a stage. The policy is cloned; the caller retains ownership.
 *
 * Stages run in the order they are added, sequentially, over one shared
 * copy-on-write upper.
 *
 * A stage this layer cannot read is DROPPED: nothing is appended and nothing
 * is reported. That is the case for a null `txn` or `policy`, for a null
 * `argv` or a null pointer inside it, for an `argc` of 0 or above 4096, and
 * for an argument whose bytes are not valid UTF-8. Dropping is the same no-op
 * a null handle already gets, and it is preferred to the alternative of
 * substituting an empty string for an argument that could not be decoded,
 * which would run a command the caller never asked for and report success.
 * A transaction that lost a stage this way does not commit silently: the core
 * sees the stage set it was actually given and refuses it.
 *
 * The cross-stage requirements (at least two stages, one shared workdir, no
 * chroot, matching storage settings) are checked by the core when the
 * transaction runs, not here, so that the caller gets the core's own
 * explanation instead of a verdict invented in this layer.
 *
 * # Safety
 * `txn` must be a valid transaction handle or null; `policy` a valid policy
 * handle or null; `argv` must be null or point to `argc` pointers, each of
 * which must itself be null or a valid C string.
 */
void sandlock_txn_add_stage(sandlock_txn_t *txn,
                            const sandlock_sandbox_t *policy,
                            const char *const *argv,
                            unsigned int argc);

/**
 * Set how long the commit may wait for the workdir lock, in milliseconds.
 *
 * Passing 0 restores the core default of 30 seconds; it does not mean "do
 * not wait". The default is a core constant that this layer cannot read, so
 * the number is spelled out here for documentation only: the value is never
 * materialised in the binding, the core supplies it.
 *
 * A consequence worth stating plainly: a zero wait, meaning one non-blocking
 * attempt at the workdir lock, cannot be asked for through this ABI. The
 * shortest wait it can express is 1.
 *
 * A null `txn` is a no-op.
 *
 * # Safety
 * `txn` must be a valid transaction handle or null.
 */
void sandlock_txn_commit_lock_wait_ms(sandlock_txn_t *txn, uint64_t ms);

/**
 * Release a transaction that was never run. A null handle is a no-op.
 *
 * # Safety
 * `txn` must be a handle from [`sandlock_txn_new`] that was not consumed by
 * a run, or null. A run consumes the handle, so calling this afterwards is a
 * double free.
 */
void sandlock_txn_free(sandlock_txn_t *txn);

/**
 * Run the transaction: every stage in turn over one shared copy-on-write
 * upper, then merge that upper into the workdir if and only if every stage
 * exited 0.
 *
 * On success returns an outcome handle and sets `*err` to 0. On failure
 * returns null, sets `*err` to a discriminant and, when `err_msg` is
 * non-null, stores an owned message the caller releases with
 * `sandlock_string_free`.
 *
 * The handle is consumed on EVERY path, including every failure, and
 * including `SANDLOCK_TXN_INVALID`, which is decided before anything runs.
 * Passing it to [`sandlock_txn_free`] afterwards is a double free and adding
 * a stage to it is a use after free; [`sandlock_txn_free`] is for the
 * build-then-abandon path only. Recovering from a rejected stage set means
 * building a new transaction, not repairing this one.
 *
 * A positive `*err` names one of the ways the core refused to carry the
 * transaction out, and always comes with a message. The two negative values
 * are not transaction verdicts and carry no message: -1 means the handle was
 * null, and -2 means this thread's async runtime could not be built or
 * panicked. Both are bugs in the caller or in its environment.
 *
 * A stage exiting non-zero, and a run that times out, are NOT failures: they
 * are an outcome whose disposition is "aborted", with `*err` still 0. The
 * workdir is untouched in both cases.
 *
 * `timeout_ms` bounds the stage phase only, never the commit; 0 means no
 * timeout. The commit phase cannot be cancelled from this ABI at all.
 *
 * Each stage's standard error is written through to this process's file
 * descriptor 2 as it is produced, as well as being captured (bounded) into
 * the stage result. Standard input and output are inherited by every stage,
 * so a stage result never carries captured stdout.
 *
 * The outcome must be released with [`sandlock_txn_outcome_free`].
 *
 * # Safety
 * `txn` must be a handle from [`sandlock_txn_new`] that has not been run or
 * freed, or null; it is consumed by this call and must not be used again.
 * `err` and `err_msg` may both be null. When `err_msg` is non-null it must
 * point to writable storage for one `*mut c_char`; it is cleared on entry.
 */
sandlock_txn_outcome_t *sandlock_txn_run(sandlock_txn_t *txn,
                                         uint64_t timeout_ms,
                                         int *err,
                                         char **err_msg);

/**
 * Run every stage exactly as [`sandlock_txn_run`] does, then report the
 * change set and discard it.
 *
 * The stages really execute; only the disposition of the shared upper
 * differs. The workdir is never written to and the commit lock is never
 * taken, so a dry run cannot conflict with anything.
 *
 * # Safety
 * As [`sandlock_txn_run`].
 */
sandlock_txn_outcome_t *sandlock_txn_dry_run(sandlock_txn_t *txn,
                                             uint64_t timeout_ms,
                                             int *err,
                                             char **err_msg);

/**
 * Which of the three terminal states the transaction ended in, as one of the
 * `SANDLOCK_TXN_DISPOSITION_*` values. Returns -1 for a null outcome.
 *
 * Why an abort happened is not published as a value here, but the two causes
 * are still tellable apart from what the outcome carries. A stage that
 * exited non-zero is reported and no later stage runs, so it is the last
 * result: walk [`sandlock_txn_outcome_stage_at`] and look for
 * `sandlock_result_success` returning false. A timeout kills the in-flight
 * stage and reports no result for it, so an aborted outcome in which every
 * reported stage succeeded is a timeout, and nothing else is.
 *
 * # Safety
 * `o` must be null or an outcome pointer that has not been freed.
 */
int sandlock_txn_outcome_disposition(const sandlock_txn_outcome_t *o);

/**
 * Number of stage results. Returns 0 for a null outcome.
 *
 * Every stage that ran is reported, including on an abort and including the
 * stages that had finished before a timeout stopped the run, so this can be
 * smaller than the number of stages that were added.
 *
 * # Safety
 * `o` must be null or an outcome pointer that has not been freed.
 */
uintptr_t sandlock_txn_outcome_stages_len(const sandlock_txn_outcome_t *o);

/**
 * The i-th stage result, in execution order, BORROWED from the outcome.
 *
 * The pointer stays valid until [`sandlock_txn_outcome_free`] and must never
 * be passed to `sandlock_result_free`. Handing out an owned clone instead
 * would copy every stage's captured output for no benefit.
 *
 * Returns null for a null outcome or an index that is out of range.
 *
 * # Safety
 * `o` must be null or an outcome pointer that has not been freed. The
 * returned pointer must not outlive `o`.
 */
const sandlock_result_t *sandlock_txn_outcome_stage_at(const sandlock_txn_outcome_t *o,
                                                       uintptr_t i);

/**
 * Number of filesystem changes the shared upper held at the end of the run.
 * Returns 0 for a null outcome.
 *
 * This is what the commit merged, or, for a dry run and for an abort, what
 * was discarded instead.
 *
 * # Safety
 * `o` must be null or an outcome pointer that has not been freed.
 */
uintptr_t sandlock_txn_outcome_changes_len(const sandlock_txn_outcome_t *o);

/**
 * Kind of the i-th change: 'A' added, 'M' modified, 'D' deleted. Returns 0
 * for a null outcome or an index that is out of range.
 *
 * # Safety
 * `o` must be null or an outcome pointer that has not been freed.
 */
char sandlock_txn_outcome_change_kind(const sandlock_txn_outcome_t *o, uintptr_t i);

/**
 * Path of the i-th change, relative to the workdir. The string is owned by
 * the caller and is released with `sandlock_string_free`. Returns null for a
 * null outcome or an index that is out of range.
 *
 * Path bytes that are not valid UTF-8 are replaced rather than preserved,
 * exactly as `sandlock_dry_run_result_change_path` does, so this is a name to
 * show a user and not always a name to open.
 *
 * # Safety
 * `o` must be null or an outcome pointer that has not been freed.
 */
char *sandlock_txn_outcome_change_path(const sandlock_txn_outcome_t *o, uintptr_t i);

/**
 * Release an outcome. A null handle is a no-op.
 *
 * Every pointer obtained from [`sandlock_txn_outcome_stage_at`] is invalid
 * afterwards.
 *
 * # Safety
 * `o` must be null or an outcome pointer from a run that has not already
 * been freed.
 */
void sandlock_txn_outcome_free(sandlock_txn_outcome_t *o);

/**
 * Sweep `storage_base` for preserved change sets.
 *
 * Returns a list handle the caller releases with
 * [`sandlock_preserved_list_free`]. Finding nothing is an EMPTY LIST, not
 * null: a base that holds no preserved work and a base that could not be read
 * (it does not exist, or is not readable) both sweep to nothing, and neither
 * is a failure of this call. Null is returned only for a null argument.
 *
 * Entries that cannot be parsed are skipped rather than failing the sweep, so
 * one broken branch directory cannot hide the rest.
 *
 * `storage_base` is read as a sequence of BYTES and is not narrowed to UTF-8:
 * a path is bytes on this platform, and this one names a directory to walk,
 * so a base another caller created is reachable whatever it is called. The
 * same holds for every path this family hands back. That is the opposite of
 * [`sandlock_txn_outcome_change_path`], which is lossy on purpose because it
 * is a name to show rather than an address to open.
 *
 * Knowing WHICH base to sweep is the caller's problem, and this ABI cannot
 * answer it: a failed commit names the preserved upper in its message and
 * nowhere else, and the default base is derived inside the core from the
 * environment. A caller that means to recover programmatically should set
 * `sandlock_sandbox_builder_fs_storage` on its policies and sweep that same
 * path, rather than parsing the message or guessing the default.
 *
 * A merge that is STILL RUNNING looks exactly like one that was interrupted:
 * the marker is written before the first destructive step. Anything that acts
 * on an entry, rather than only reporting it, must first check that
 * [`sandlock_preserved_pid`] is not a live process.
 *
 * # Safety
 * `storage_base` must be null or a valid C string.
 */
sandlock_preserved_list_t *sandlock_preserved_list(const char *storage_base);

/**
 * Number of preserved change sets in the sweep. 0 for a null list.
 *
 * # Safety
 * `l` must be null or a list pointer that has not been freed.
 */
uintptr_t sandlock_preserved_list_len(const sandlock_preserved_list_t *l);

/**
 * The i-th preserved change set, BORROWED from the list.
 *
 * The pointer stays valid until [`sandlock_preserved_list_free`] and must
 * NEVER be passed to [`sandlock_preserved_free`]: it is not a separate
 * allocation, and freeing it would free memory the list still owns. Only a
 * handle from [`sandlock_preserved_read`] is freed that way.
 *
 * Returns null for a null list or an index that is out of range.
 *
 * # Safety
 * `l` must be null or a list pointer that has not been freed. The returned
 * pointer must not outlive `l`.
 */
const sandlock_preserved_t *sandlock_preserved_list_at(const sandlock_preserved_list_t *l,
                                                       uintptr_t i);

/**
 * Read one preserved change set from its branch directory.
 *
 * Returns an OWNED handle the caller releases with
 * [`sandlock_preserved_free`], which is the one handle that may be freed that
 * way.
 *
 * Null means the directory is not a usable preserved branch: it is null or
 * unreadable, it holds no marker, it is the live storage of a running
 * process, or its marker was cut short by a crash. Those cases are not
 * distinguishable here, deliberately: a half-parsed record is worse than none
 * at all, because acting on it would target the wrong workdir.
 *
 * `branch_dir` is read as a sequence of BYTES, not narrowed to UTF-8, so what
 * [`sandlock_preserved_branch_dir`] reported can be fed straight back here.
 *
 * # Safety
 * `branch_dir` must be null or a valid C string.
 */
sandlock_preserved_t *sandlock_preserved_read(const char *branch_dir);

/**
 * The branch's private storage directory: what to remove once the change set
 * has been recovered, and what [`sandlock_preserved_read`] takes.
 *
 * The string is OWNED by the caller and is released with
 * `sandlock_string_free`, whether the record came from a list borrow or from
 * a read. Freeing the record does not free strings already handed out, and
 * freeing a string does not touch the record. Returns null for a null record.
 *
 * It carries the path's BYTES verbatim and may therefore not be valid UTF-8.
 * A binding must keep those bytes rather than decode them: this is the string
 * that goes back into [`sandlock_preserved_read`] and that names the directory
 * to remove once the change set has been recovered, so a substituted character
 * would name a directory that does not exist. Every path this family returns
 * works the same way, and none of them is like
 * [`sandlock_txn_outcome_change_path`], which is lossy because it is a name to
 * show rather than an address to open.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
char *sandlock_preserved_branch_dir(const sandlock_preserved_t *p);

/**
 * The upper holding the preserved additions and modifications.
 *
 * This is only half of the change set: the deletions have no representation
 * here at all, so copying this upper over the workdir and nothing else would
 * resurrect every file the run removed. See
 * [`sandlock_preserved_deleted_at`], and apply deletions FIRST.
 *
 * Owned string, released with `sandlock_string_free`, carrying the path's
 * bytes verbatim (see [`sandlock_preserved_branch_dir`]). Null for a null
 * record.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
char *sandlock_preserved_upper(const sandlock_preserved_t *p);

/**
 * The workdir the change set belongs to, canonicalized when the branch was
 * created.
 *
 * Owned string, released with `sandlock_string_free`, carrying the path's
 * bytes verbatim (see [`sandlock_preserved_branch_dir`]). Null for a null
 * record.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
char *sandlock_preserved_workdir(const sandlock_preserved_t *p);

/**
 * Why the change set was preserved, as one of the
 * `SANDLOCK_PRESERVE_*` values. Returns -1 for a null record.
 *
 * This is what says how far the workdir got, so a recovery has to read it
 * before it reads anything else; `SANDLOCK_PRESERVE_MERGE_INTERRUPTED` is
 * also what a merge that is still running looks like, and see
 * [`sandlock_preserved_pid`] for why that matters.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
int sandlock_preserved_reason(const sandlock_preserved_t *p);

/**
 * The process that preserved the change set. 0 for a null record, which is
 * not a process id anything here can have.
 *
 * Load-bearing for one thing: a merge writes its marker BEFORE its first
 * destructive step, so a merge in flight and a merge that was interrupted are
 * the same record, and this pid is the only thing that tells them apart.
 * Anything that acts on such a record must check that the pid is not live
 * first. Beyond that it is triage only: the process may be long gone and its
 * pid reused.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
uint32_t sandlock_preserved_pid(const sandlock_preserved_t *p);

/**
 * Number of paths the run deleted. 0 for a null record.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
uintptr_t sandlock_preserved_deleted_len(const sandlock_preserved_t *p);

/**
 * The i-th deleted path, relative to the workdir, in sorted order.
 *
 * These are the outstanding deletions as of the last write of the record, and
 * they are the half of the change set that the upper cannot carry. A recovery
 * applies them BEFORE the upper: an addition under a path the run also
 * deleted only lands correctly once that path has been emptied.
 *
 * Owned string, released with `sandlock_string_free`, carrying the path's
 * bytes verbatim (see [`sandlock_preserved_branch_dir`]). Null for a null
 * record or an index that is out of range.
 *
 * # Safety
 * `p` must be null or a record pointer that has not been freed.
 */
char *sandlock_preserved_deleted_at(const sandlock_preserved_t *p, uintptr_t i);

/**
 * Release a sweep. A null list is a no-op.
 *
 * Every pointer obtained from [`sandlock_preserved_list_at`] is invalid
 * afterwards. Strings already handed out by the accessors are not: they are
 * separate allocations the caller still owns and still has to free.
 *
 * This does not remove anything from disk. The preserved storage outlives the
 * sweep, and removing it is the caller's decision once the change set has
 * been recovered.
 *
 * # Safety
 * `l` must be null or a list from [`sandlock_preserved_list`] that has not
 * already been freed.
 */
void sandlock_preserved_list_free(sandlock_preserved_list_t *l);

/**
 * Release a record from [`sandlock_preserved_read`]. A null record is a
 * no-op.
 *
 * ONLY for a handle from [`sandlock_preserved_read`]. A pointer from
 * [`sandlock_preserved_list_at`] borrows from its list and passing it here is
 * a double free; that list is released by [`sandlock_preserved_list_free`]
 * instead.
 *
 * This does not remove anything from disk, for the same reason
 * [`sandlock_preserved_list_free`] does not.
 *
 * # Safety
 * `p` must be null or a record from [`sandlock_preserved_read`] that has not
 * already been freed.
 */
void sandlock_preserved_free(sandlock_preserved_t *p);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SANDLOCK_H */
